packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"

catalog:
  react: "^19.2.0"
  react-dom: "^19.2.0"
  "@types/react": "^19.2.0"
  "@types/react-dom": "^19.2.0"
  typescript: "^5.9.0"
  tsup: "^8.0.0"
  vitest: "^4.0.0"
  jsdom: "^28.1.0"
  "@testing-library/react": "^16.3.0"
  "@testing-library/jest-dom": "^6.9.0"
  "@testing-library/user-event": "^14.6.0"
  vitest-axe: "^0.1.0"
  class-variance-authority: "^0.7.0"
  tailwind-merge: "^2.0.0"
  react-aria: "^3.46.0"
  react-stately: "^3.44.0"
  tailwindcss: "^4.0.0"
  "@tailwindcss/postcss": "^4.0.0"
  "@tailwindcss/vite": "^4.0.0"
  postcss: "^8.4.0"
  vite: "^7.3.0"
  "@vitejs/plugin-react": "^5.1.0"
  tsx: "^4.0.0"
