name: Feature Request
description: Suggest a new feature or enhancement
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - "New component"
        - "Existing component improvement"
        - "Theming / tokens"
        - "Agent system"
        - "Accessibility"
        - "Documentation"
        - "DX / tooling"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? Is it related to a specific use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to open a pull request for this feature
